In [4]:
print("spermulaan")

spermulaan


Mengimport package numpy dipython

In [2]:
import numpy as np

membuat vektor 

In [3]:
A = np.array([1,2,3,4,5])
B = np.array([1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5])
print(A)
print(B)

[1 2 3 4 5]
[1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


membuat vektor dengan range

In [4]:
C = np.arange(1,20,3)# vektor dengan rangkap 3
D = np.arange(1,15,0.5)# vektor dengan rangkap 0,5
print(C)
print(D)

[ 1  4  7 10 13 16 19]
[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5]


membuat vektor dengan linspace

Fungsi linspace dalam NumPy digunakan untuk membuat array berisi deret bilangan dengan jarak yang sama antara nilai awal dan akhir yang ditentukan. Istilah "linspace" sendiri adalah singkatan dari "linear space", yang menunjukkan bahwa bilangan dalam array yang dihasilkan akan memiliki jarak yang sama di antara mereka.

In [5]:
E = np.linspace(1,20,15)
F = np.linspace(1,10,4)
print(E)
print(F)

[ 1.          2.35714286  3.71428571  5.07142857  6.42857143  7.78571429
  9.14285714 10.5        11.85714286 13.21428571 14.57142857 15.92857143
 17.28571429 18.64285714 20.        ]
[ 1.  4.  7. 10.]


Membuat array multidimensi / matrix

In [6]:
G = np.array([(1,2,3,4,5), (6,7,8,9,10)])
H = np.array([(1,2,3,4,5), (6,7,8,9,10)])
print(G)
print(H+3) # jika matrix H ditambahkan angka berapapun maka semua komponen yang ada 
           # di dalam matrix tersebut akan di tambah 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 4  5  6  7  8]
 [ 9 10 11 12 13]]


membuat matrix dengan nilai 0 menggunakan package zeros 

fungsi zeros digunakan untuk membuat array berisi nol

In [7]:
I = np.zeros(5)
J = np.zeros((4,4))
print(I)
print(J)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


membuat matrix dengan nilai 0 menggunakan package ones

 fungsi ones digunakan untuk membuat array berisi satu

In [11]:
K = np.zeros(3)
L = np.zeros((4,8))
M = np.full((4,8), 3)# full digunakan untuk mengisi semua elemen dalam matrix dengan angka tertentu
print(K)
print(L)
print(M)

[0. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3]]


membuat matrix identity / identitas 

In [12]:
N = np.identity(4)
print(N)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
