In [2]:
import numpy as np

perbedaan menggunakan array pada python dan numpy

In [4]:
# 1. penjumlahan 
#list array pada python
A = [20,13,15,30,10]
B = [10,20,30,40,50]

#list array pada numpy
AN = np.array([20,13,15,30,10])
BN = np.array([10,20,30,40,50])

# hasil pada array python
print("============hasil array python============")
hasil1 = A+B
print(hasil1)

# hasil pada array numpy
print("============hasil array numpy=============")
hasil2 = AN+BN
print(hasil2)

============hasil array python============
[20, 13, 15, 30, 10, 10, 20, 30, 40, 50]
============hasil array numpy============
[30 33 45 70 60]


In [6]:
# 2. pengurangan

#list array pada numpy
AN = np.array([20,13,15,30,10])
BN = np.array([10,20,30,40,50])

# hasil pada array numpy
print("============hasil array numpy=============")
hasil2 = AN-BN
print(hasil2)

============hasil array numpy=============
[ 10  -7 -15 -10 -40]


In [7]:
# 3. pembagian

#list array pada numpy
AN = np.array([20,13,15,30,10])
BN = np.array([10,20,30,40,50])

# hasil pada array numpy
print("============hasil array numpy=============")
hasil2 = AN / BN
print(hasil2)

============hasil array numpy=============
[2.   0.65 0.5  0.75 0.2 ]


In [8]:
# 4. perkalian
#list array pada numpy
AN = np.array([20,13,15,30,10])
BN = np.array([10,20,30,40,50])

# hasil pada array numpy
print("============hasil array numpy=============")
hasil2 = AN * BN
print(hasil2)

============hasil array numpy=============
[ 200  260  450 1200  500]


In [10]:
# 5. Kuadrat
#list array pada numpy
AN = np.array([20,13,15,30,10])
BN = np.array([10,20,30,40,50])

# hasil pada array numpy
print("============hasil array numpy=============")
hasil1 = AN**2
hasil2 = BN**2
hasil3 = hasil1 + hasil2
print(hasil1)
print(hasil2)
print(hasil3)


============hasil array numpy=============
[400 169 225 900 100]
[ 100  400  900 1600 2500]
[ 500  569 1125 2500 2600]


In [11]:
# 6. operasi matematik pada matrix 
AN = np.array(([20,13,15,30,10],[10,20,30,40,50]))
BN = np.array(([10,20,30,40,50],[20,13,15,30,10]))
hasil = AN + BN
print(hasil)

[[30 33 45 70 60]
 [30 33 45 70 60]]
